/**
 * Pawday's vector animation layer.
 *
 * The animations are Lottie files generated by `tools/make-lottie.mjs` and
 * committed under `assets/lottie`, so nothing is fetched at runtime and nothing
 * is licensed from a marketplace.
 *
 * The player itself comes from `lottie-player`, which resolves to the real
 * `lottie-react-native` on native and to nothing on web — see that file for
 * why. When it is unavailable, every call site falls back to the emoji or icon
 * it was decorating in the first place, so the UI stays complete and simply
 * stops moving.
 */

import React, { useEffect, useRef } from 'react';
import { Animated, Easing, Platform, Pressable, View, ViewStyle } from 'react-native';
import { useApp } from './AppContext';
import { LottiePlayer } from './lottie-player';

export type AnimationName =
  | 'paw-check'
  | 'confetti'
  | 'streak-flame'
  | 'heart-pulse'
  | 'trophy-sparkle'
  | 'paw-trail'
  | 'coin-flip';

const SOURCES: Record<AnimationName, unknown> = {
  'paw-check': require('../assets/lottie/paw-check.json'),
  confetti: require('../assets/lottie/confetti.json'),
  'streak-flame': require('../assets/lottie/streak-flame.json'),
  'heart-pulse': require('../assets/lottie/heart-pulse.json'),
  'trophy-sparkle': require('../assets/lottie/trophy-sparkle.json'),
  'paw-trail': require('../assets/lottie/paw-trail.json'),
  'coin-flip': require('../assets/lottie/coin-flip.json'),
};

/**
 * Layer names to re-tint per animation, matching the names the generator
 * writes. `colorFilters` is how one file serves six theme packs; it is a native
 * feature, and unfiltered playback still looks right because the baked colours
 * are the default theme's.
 */
const TINTABLE: Partial<Record<AnimationName, string[]>> = {
  'paw-check': ['ring', 'paw'],
  'coin-flip': ['coin'],
  'trophy-sparkle': ['cup', 'sparkle-a', 'sparkle-b', 'sparkle-c'],
  'paw-trail': ['print-0', 'print-1', 'print-2', 'print-3', 'print-4', 'print-5'],
};

export const lottieAvailable = Boolean(LottiePlayer);

export function Anim({
  name,
  size = 96,
  loop = false,
  autoPlay = true,
  speed = 1,
  tint,
  style,
  onFinish,
  fallback = null,
}: {
  name: AnimationName;
  size?: number;
  loop?: boolean;
  autoPlay?: boolean;
  speed?: number;
  /** Re-tints the animation's named layers; defaults to the file's own colours. */
  tint?: string;
  style?: ViewStyle;
  onFinish?: () => void;
  /** Shown when animation is off or the player is unavailable. */
  fallback?: React.ReactNode;
}) {
  const { state } = useApp();
  const enabled = state.settings.motion && lottieAvailable;

  // A one-shot animation is often what tells the caller something finished. If
  // it cannot play, say so on the same schedule so cleanup still happens.
  useEffect(() => {
    if (enabled || loop || !onFinish) return undefined;
    const timer = setTimeout(onFinish, 400);
    return () => clearTimeout(timer);
  }, [enabled, loop, onFinish]);

  if (!enabled) {
    return fallback ? <View style={[{ width: size, height: size, alignItems: 'center', justifyContent: 'center' }, style]}>{fallback}</View> : null;
  }

  const keypaths = tint ? TINTABLE[name] : undefined;
  return (
    <LottiePlayer
      source={SOURCES[name]}
      autoPlay={autoPlay}
      loop={loop}
      speed={speed}
      resizeMode="contain"
      colorFilters={keypaths?.map(keypath => ({ keypath, color: tint }))}
      onAnimationFinish={loop ? undefined : onFinish}
      style={[{ width: size, height: size }, style]}
    />
  );
}

/**
 * A cheap always-available flourish for freshly changed values — a scale nudge
 * driven by `Animated`, so it works on web and survives animation being off as
 * a plain static render.
 *
 * Lottie handles the set-piece celebrations; this handles the hundred small
 * moments where a number changed and the eye should be told where to look.
 */
export function Nudge({
  children,
  trigger,
  amount = 0.16,
  style,
}: {
  children: React.ReactNode;
  /** Re-runs whenever this value changes. */
  trigger: unknown;
  amount?: number;
  style?: ViewStyle;
}) {
  const { state } = useApp();
  const motion = state.settings.motion;
  const scale = useRef(new Animated.Value(1)).current;
  const first = useRef(true);

  useEffect(() => {
    if (first.current) {
      first.current = false;
      return;
    }
    if (!motion) return;
    Animated.sequence([
      Animated.timing(scale, { toValue: 1 + amount, duration: 130, easing: Easing.out(Easing.quad), useNativeDriver: true }),
      Animated.spring(scale, { toValue: 1, friction: 4, tension: 180, useNativeDriver: true }),
    ]).start();
  }, [amount, motion, scale, trigger]);

  return <Animated.View style={[{ transform: [{ scale }] }, style]}>{children}</Animated.View>;
}

/**
 * Animated style for a control that should dip under the finger.
 *
 * Web has hover to carry affordance; touch has only this, which is why it is
 * worth a hook. Returns a style object to spread onto an animated component, so
 * the caller keeps its own layout contract — wrapping buttons in an extra view
 * breaks `flex: 1` and `alignSelf: 'stretch'` at half the call sites.
 */
export function usePressScale(pressed: boolean, depth = 0.97) {
  const { state } = useApp();
  const motion = state.settings.motion;
  const scale = useRef(new Animated.Value(1)).current;

  useEffect(() => {
    if (!motion) return;
    Animated.spring(scale, {
      toValue: pressed ? depth : 1,
      friction: 7,
      tension: 220,
      useNativeDriver: true,
    }).start();
  }, [depth, motion, pressed, scale]);

  return { transform: [{ scale }] };
}

/** `Pressable` that can take the animated style from `usePressScale`. */
export const AnimatedPressable = Animated.createAnimatedComponent(Pressable);

/** Whether the platform can play Lottie at all — surfaced in Settings so the toggle can explain itself. */
export const MOTION_PLATFORM_NOTE = lottieAvailable
  ? undefined
  : Platform.OS === 'web'
    ? 'Vector animations are native-only in this build; the web preview uses the static icons.'
    : 'Vector animations need a native rebuild to appear.';
